-- liquibase formatted sql

-- changeset helcio:280820221405-1
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset helcio:280820221405-2
CREATE TABLE public.cities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    state_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

-- changeset helcio:280820221405-3
CREATE TABLE public.countries
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

-- changeset helcio:280820221405-4
CREATE TABLE public.documents
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT                                  NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    value       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

-- changeset helcio:280820221405-5
CREATE TABLE public.events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(1024)                           NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated         TIMESTAMP WITHOUT TIME ZONE,
    removed         BOOLEAN,
    remove_date     TIMESTAMP WITHOUT TIME ZONE,
    location_id     BIGINT,
    owner_id        BIGINT                                  NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    attendance_mode VARCHAR(255)                            NOT NULL,
    start_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

-- changeset helcio:280820221405-6
CREATE TABLE public.events_organizers
(
    event_id     BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,
    CONSTRAINT pk_events_organizers PRIMARY KEY (event_id, organizer_id)
);

-- changeset helcio:280820221405-7
CREATE TABLE public.languages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

-- changeset helcio:280820221405-8
CREATE TABLE public.lectures
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(1024)                           NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated         TIMESTAMP WITHOUT TIME ZONE,
    removed         BOOLEAN,
    remove_date     TIMESTAMP WITHOUT TIME ZONE,
    event_id        BIGINT                                  NOT NULL,
    language_id     BIGINT,
    room_id         BIGINT,
    attendance_mode VARCHAR(255)                            NOT NULL,
    start_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_lectures PRIMARY KEY (id)
);

-- changeset helcio:280820221405-9
CREATE TABLE public.lectures_participants
(
    lecture_id     BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    CONSTRAINT pk_lectures_participants PRIMARY KEY (lecture_id, participant_id)
);

-- changeset helcio:280820221405-10
CREATE TABLE public.lectures_speakers
(
    lecture_id BIGINT NOT NULL,
    speaker_id BIGINT NOT NULL,
    CONSTRAINT pk_lectures_speakers PRIMARY KEY (lecture_id, speaker_id)
);

-- changeset helcio:280820221405-11
CREATE TABLE public.lectures_tags
(
    lecture_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    CONSTRAINT pk_lectures_tags PRIMARY KEY (lecture_id, tag_id)
);

-- changeset helcio:280820221405-12
CREATE TABLE public.rooms
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    event_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

-- changeset helcio:280820221405-13
CREATE TABLE public.states
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    country_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_states PRIMARY KEY (id)
);

-- changeset helcio:280820221405-14
CREATE TABLE public.tags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

-- changeset helcio:280820221405-15
CREATE TABLE public.users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    removed     BOOLEAN,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    admin       BOOLEAN                                 NOT NULL,
    location_id BIGINT,
    username    VARCHAR(32)                             NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    telephone   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset helcio:280820221405-16
ALTER TABLE role
    ADD CONSTRAINT uc_role_id UNIQUE (id);

-- changeset helcio:280820221405-17
ALTER TABLE public.states
    ADD CONSTRAINT uc_001ccadf1dce53cc6b739b27f UNIQUE (name, country_id);

-- changeset helcio:280820221405-18
ALTER TABLE public.tags
    ADD CONSTRAINT uc_18db57ffdcc75533c0d7095a8 UNIQUE (name);

-- changeset helcio:280820221405-19
ALTER TABLE public.lectures
    ADD CONSTRAINT uc_56e8478252ff2ba3c368a8a04 UNIQUE (name, event_id);

-- changeset helcio:280820221405-20
ALTER TABLE public.cities
    ADD CONSTRAINT uc_921bd305f716e7decc11cf378 UNIQUE (name, state_id);

-- changeset helcio:280820221405-21
ALTER TABLE public.documents
    ADD CONSTRAINT uc_9e3550254c5757d0ce3382336 UNIQUE (user_id, type);

-- changeset helcio:280820221405-22
ALTER TABLE public.rooms
    ADD CONSTRAINT uc_b61fd80e31c73237f7347b28d UNIQUE (name, event_id);

-- changeset helcio:280820221405-23
ALTER TABLE public.cities
    ADD CONSTRAINT uc_cities_id UNIQUE (id);

-- changeset helcio:280820221405-24
ALTER TABLE public.countries
    ADD CONSTRAINT uc_countries_id UNIQUE (id);

-- changeset helcio:280820221405-25
ALTER TABLE public.documents
    ADD CONSTRAINT uc_documents_id UNIQUE (id);

-- changeset helcio:280820221405-26
ALTER TABLE public.events
    ADD CONSTRAINT uc_events_id UNIQUE (id);

-- changeset helcio:280820221405-27
ALTER TABLE public.events_organizers
    ADD CONSTRAINT uc_events_organizers_event UNIQUE (event_id);

-- changeset helcio:280820221405-28
ALTER TABLE public.countries
    ADD CONSTRAINT uc_f054a373c493c6244e7163abe UNIQUE (name);

-- changeset helcio:280820221405-29
ALTER TABLE public.languages
    ADD CONSTRAINT uc_f0772c60f542a7b9fa59d415b UNIQUE (name);

-- changeset helcio:280820221405-30
ALTER TABLE public.languages
    ADD CONSTRAINT uc_languages_id UNIQUE (id);

-- changeset helcio:280820221405-31
ALTER TABLE public.lectures
    ADD CONSTRAINT uc_lectures_id UNIQUE (id);

-- changeset helcio:280820221405-32
ALTER TABLE public.lectures_participants
    ADD CONSTRAINT uc_lectures_participants_lecture UNIQUE (lecture_id);

-- changeset helcio:280820221405-33
ALTER TABLE public.lectures_speakers
    ADD CONSTRAINT uc_lectures_speakers_lecture UNIQUE (lecture_id);

-- changeset helcio:280820221405-34
ALTER TABLE public.lectures_tags
    ADD CONSTRAINT uc_lectures_tags_lecture UNIQUE (lecture_id);

-- changeset helcio:280820221405-35
ALTER TABLE public.rooms
    ADD CONSTRAINT uc_rooms_id UNIQUE (id);

-- changeset helcio:280820221405-36
ALTER TABLE public.states
    ADD CONSTRAINT uc_states_id UNIQUE (id);

-- changeset helcio:280820221405-37
ALTER TABLE public.tags
    ADD CONSTRAINT uc_tags_id UNIQUE (id);

-- changeset helcio:280820221405-38
ALTER TABLE public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset helcio:280820221405-39
ALTER TABLE public.users
    ADD CONSTRAINT uc_users_id UNIQUE (id);

-- changeset helcio:280820221405-40
ALTER TABLE public.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset helcio:280820221405-41
ALTER TABLE public.cities
    ADD CONSTRAINT FK_CITIES_ON_STATE FOREIGN KEY (state_id) REFERENCES public.states (id);

-- changeset helcio:280820221405-42
ALTER TABLE public.documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES public.users (id);

-- changeset helcio:280820221405-43
ALTER TABLE public.events
    ADD CONSTRAINT FK_EVENTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES public.cities (id);

-- changeset helcio:280820221405-44
ALTER TABLE public.events
    ADD CONSTRAINT FK_EVENTS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES public.users (id);

-- changeset helcio:280820221405-45
ALTER TABLE public.lectures
    ADD CONSTRAINT FK_LECTURES_ON_EVENT FOREIGN KEY (event_id) REFERENCES public.events (id);

-- changeset helcio:280820221405-46
ALTER TABLE public.lectures
    ADD CONSTRAINT FK_LECTURES_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES public.languages (id);

-- changeset helcio:280820221405-47
ALTER TABLE public.lectures
    ADD CONSTRAINT FK_LECTURES_ON_ROOM FOREIGN KEY (room_id) REFERENCES public.rooms (id);

-- changeset helcio:280820221405-48
ALTER TABLE public.rooms
    ADD CONSTRAINT FK_ROOMS_ON_EVENT FOREIGN KEY (event_id) REFERENCES public.events (id);

-- changeset helcio:280820221405-49
ALTER TABLE public.states
    ADD CONSTRAINT FK_STATES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES public.countries (id);

-- changeset helcio:280820221405-50
ALTER TABLE public.users
    ADD CONSTRAINT FK_USERS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES public.cities (id);

-- changeset helcio:280820221405-51
ALTER TABLE public.events_organizers
    ADD CONSTRAINT fk_eveorg_on_event FOREIGN KEY (event_id) REFERENCES public.events (id);

-- changeset helcio:280820221405-52
ALTER TABLE public.events_organizers
    ADD CONSTRAINT fk_eveorg_on_user FOREIGN KEY (organizer_id) REFERENCES public.users (id);

-- changeset helcio:280820221405-53
ALTER TABLE public.lectures_participants
    ADD CONSTRAINT fk_lecpar_on_lecture FOREIGN KEY (lecture_id) REFERENCES public.lectures (id);

-- changeset helcio:280820221405-54
ALTER TABLE public.lectures_participants
    ADD CONSTRAINT fk_lecpar_on_user FOREIGN KEY (participant_id) REFERENCES public.users (id);

-- changeset helcio:280820221405-55
ALTER TABLE public.lectures_speakers
    ADD CONSTRAINT fk_lecspe_on_lecture FOREIGN KEY (lecture_id) REFERENCES public.lectures (id);

-- changeset helcio:280820221405-56
ALTER TABLE public.lectures_speakers
    ADD CONSTRAINT fk_lecspe_on_user FOREIGN KEY (speaker_id) REFERENCES public.users (id);

-- changeset helcio:280820221405-57
ALTER TABLE public.lectures_tags
    ADD CONSTRAINT fk_lectag_on_lecture FOREIGN KEY (lecture_id) REFERENCES public.lectures (id);

-- changeset helcio:280820221405-58
ALTER TABLE public.lectures_tags
    ADD CONSTRAINT fk_lectag_on_tag FOREIGN KEY (tag_id) REFERENCES public.tags (id);

